package com.bbarg.bloodborneargentina.bbarg.Models;

public class LoreBodies {

    private String lore_1;
    private String lore_2;

    public LoreBodies() {
        lore_1 = "“Byrgenwerh es un antiguo lugar de aprendizaje.  Y la tumba de los dioses, tallada debajo de Yharnam, debería ser familiar para cada cazador Bueno… una vez un grupo de escolares d Byrgenwerth descubrió un médium sagrado profundo dentro de la tumba. Esto provoco la fundación d la Iglesia de la Sanacion y el establecimiento de la sanación por sangre. En este sentido, todo lo sagrado en Yharnam puede ser trazado hacia byrgenwerth.\"\n" +
                "Alfred, Cazador Vileblood.\n" +
                "\n" +
                "Todo comienza en Byrgenwerth. Una vieja institución de aprendizaje, ésta fue construida en una área apartada, lejos de la ciudad vecina y cerca de un gran lago. Es aquí que un grupo de individuos estudio y exploro las profundidades del conocimiento humano.\n" +
                "(Aquí aclara que solo utilizara info dentro del juego, sin dar lugar a interpretaciones personales)\n" +
                "\n" +
                "Habia muchos estudiantes en Byrgenwerth  y un grupo de individuos notables mas allá de los estudiantes. Figuras de importancia que formaron el circulo interior por llamarlo de alguna forma.\n" +
                "Estos individuos podemos deducir que eran Willem, Laurence, Micolash y Carryl.\n" +
                "El maestro Willem era la cabeza de la academia y una figura altamente respetada. \n" +
                "Todos los personajes que se refieren a el, lo hacen como MAESTRO Willem, demostrando un profundo respeto por la figura, aun si tenían diferencias en sus creencias. También hay una referencia en el taller de Runas que lo llama Preboste Willem. Un preboste es un administrador de una institución académica, lo que avala la posición de este como la cabeza de Byrgenwerth. Su enfoque principal era el estudio de los limites de la inteligencia humana.\n" +
                " Laurence es una figura mucho mas enigmática, especialmente para ser un personaje tan importante. \n" +
                "Desde el cráneo de bestia en la Gran Catedral, el Cazador protagonista, presencia una memoria de un encuentro entre Laurence y Willem, en el que este ultimo, acusa a un joven Laurence de traicionarlo. Una nota dejada en la escalinata de la catedral lee “Pon tu mano en el cubrimiento sagrado del altar, e inscribe el adagio del Maestro Laurence en tu carne”. Que Laurence seria reverado de tal manera, infiere que el debería haber sido una figura muy importante en la Iglesia de la sanación. Es bien documentado que la Iglesia de la Sanacion tiene sus raíces en Byrgenwerth. \n" +
                "El uniforme de estudiante reza:\n" +
                "“La Iglesia de la Sanacion tiene sus raíces en Byrgenwerth, y naturalmente toma prestado mucho de su diseño en el uniforme. El enfoque no en conocimiento o pensamiento, pero en pura pretencion, seguramente traerían al Maestro Willem a la desesperación. Si tan solo supiera”\n" +
                "\n" +
                "El titulo de Laurence de “Primer Vicario” dado a el por ambos, el cráneo humano de la pesadilla y en su BOSS FIGHT, confirmando la idea de que Laurence fue, de hecho, uno de los fundadores de la Iglesia. Dividiendose de Byrgenwerth en un evento que mas tarde describiré como “la cisma”\n" +
                " Micolash, el boss encontrado en la pesadilla de Mensis, era otro escolar, como es evidenciado por su uniforme deteriorado de Byrgenwerth. \n" +
                " Carryl era un/a genio/a artesano/a quien, a través de métodos desconocidos, podía escuchar los rasguños y murmullos de los Grandes. \n" +
                "Si bien no podía entender las palabras inhumanas que hablaban, ella logro sellarlas en símbolos visuales que podían ser identificados. \n" +
                "La herramienta de las runas describe a Carryl como “estudiante de Byrgenwerth, transcribió los murmullos inhumanos de los Grandes en lo que ahora llamamos las Runas Carryl”\n" +
                " También existen 2 individuos quienes podemos llegar a creer que fueron miembros de los Escolares, Gehrman y Maria.\n" +
                "\n" +
                "Gehrman era seguramente un conocido de Laurence y Willem, podemos encontrar a Gehrman, hablando dormido, “Oh Laurence, Maestro Willem, alguien ayúdeme”. Este es también conocido como el Primer Cazador. El fundo el Taller localizado en una ubicación secreta de Upper Cathedral Ward, y presuntamente trabajo con la Iglesia en su juventud. Juzgando por la habilidad de combate y maestría en confección, el tranquilamente pudo haber sido un guardaespaldas para las excavaciones de las tumbas, un celador o un “arreglatodo” para la universidad en general.\n" +
                " Maria era el discípulo mas grande de Gehrman, y juzgando por el hecho que toma el Research Hall de la Iglesia de la Sanacion, es posible que haya sido un estudiante en Byrgenwerth bajo el tutelaje de Laurence. De todos modos, su participación en los eventos que tomarían lugar en la Aldea Pesquera la ponen como miembro de Byrgenwerth antes de su cisma.\n" +
                " Ahora podemos mirar a los Escolares, habiendo explorado a cada uno individualmente, como una unidad colectiva. Willem, Laurence, Micolash, Gehrman, Maria y Carryl eran parte de esta institución dedicada a expandir el conocimiento y la exploración del masivo laberinto construido bajo tierra. Fue en ese laberinto que los escolares hicieron el descubrimiento que pondrían cada evento en Bloodborne en marcha. Es mas, toda la historia de Bloodborne data de un momento definitivo, en que los Escolares descubrieron algo, en lo profundo de las criptas Pthumerianas. \n" +
                "Ademas, dentro del laberinto, los escolares descubrieron la Antigua Sangre.\n" +
                "No queda en claro exactamente que es lo que se encontró, pero en el nivel superior de  Byrgenwerth, podemos encontrar la Concha Vacia “Concha de inverterado vacio que dice ser un familiar de un Grande. La iglesia de la Sanacion ha descubierto una gran variedad de invertebrados o fantasmas, como son llamados”. \n" +
                "Lo que haya sido encontrado, era prueba de la existencia de los Grandes. Es posible que los escolares hayan descubierto a Ebrietas, el abandonado Grande que mas tarde comulgaría con la Iglesia de la Sanación. Ciertamente descubrieron una fuente de la Sangre Antigua, la manchada sangre de los Grandes. Si fue Ebrietas o alguien mas, no queda claro.\n" +
                "Sucesos derivados del contacto con los laberintos:\n" +
                "Con el descubrimiento de la Sangre Antigua y de los Grandes, todo cambio.\n" +
                "La evolución se transformo en la meta. Empujar los limites de la humanidad y convertirse en algo superior. Ascender al nivel de los Grandes, empujar la humanidad a su próximo nivel. Una nota garabateada encontrada en el Edificio de Conferencias de la pesadilla lee: “El Maestro Willem tenia razón. Evolucion sin coraje será la ruina de nuestra raza”. Sin embargo, se hizo aparente muy pronto que algunos de los Escolares, y Laurence en particular, diferían en sus creencias en como la evolución debería ocurrir. \n" +
                "La Runa del Ojo dice: “Los ojos simbolizan la verdad que el Maestro Willem busco en su investigación. Desilusionado por los limites del intelecto humando, Maestro Willem miro a los seres de planos superiores por guía y busco alinear su cerebro con ojos con el fin de elevar sus pensamientos”. \n" +
                "Sin embargo, la Runa de Metamorfosis  reza: “El descubrimiento de sangre hizo sus sueños de evolución una realidad. Metamorfosis y los excesos y deviación que siguieron, fueron solo el comienzo”.\n" +
                " Hay 2 diferentes recursos que el jugador recolecta durante su tiempo en Bloodborne. Ecos de Sangre y Lucidez. Los ecos son el método mediante el cual el Cazador gana poder, mientras que la Lucidez es el método   mediante el cual obtiene conocimiento. \n" +
                "Mientras algunos en Byrgenwerth creían que el conocimiento y comprensión de los Grandes y los altos planos de existencia guiarían al ascenso de la humanidad. Otros creían que era a través de la fusión con la sangre antigua que llevaría a esto. Este era un concepto anatema a todo lo que Willem representaba.\n" +
                "Teme a la Sangre Antigua.\n" +
                "Estas dos filosofías fundamentalmente opuestas, provocarían \"al cisma\" de Byrgenwerth. Pero hay otra pieza en el rompecabezas.\n" +
                "\n" +
                "Tras entrar en la Aldea pesquera en la Pesarilla del cazador, el protagonista es saludado por un Pez Semejante, murmurando para si mismo: “Byrgenwerth, Byrgenwerth, trastornados por la sangre asesinos, bestias blasfemas”. Si el jugador esta usando la Runa \"Nutricion\", el semejante les dará un cráneo que reza: “calavera de un local de la violada aldea pesquera. El interior del cráneo fue hurgado buscando sus ojos, siendo evidencia, los innumerables rasguños y rayas” Lo que sea que aconteció en la Aldea Pesquera, debe haber tenido que ver con Kos, el Grande encontrado al fin del área. Kos esta aparentemente muerto y mientras el cazador pelea con su Huérfano, el Grande hace tiempo ha muerto. Sin contar con los balbuceos del Pez Semejante, solo hay una referencia mas a Kos, la de Micolash en su comunión con el Cosmos, “Ahh, Kos, o como algunos la llaman Kosm… Escuchas nuestras oraciones? Como hiciste una vez con la vacua Rom, concedenos ojos, concedenos ojos”\n" +
                " Rom, como encontramos, es una gran criatura que es vista en el fondo del Lago lugar de Byrgenwerth. El titulo de Rom es el de \"la Araña Vacua\", y muestra ser relativamente débil. \n" +
                "La única fortaleza que tiene viene de las arañas Parientes que puede spawnear para defenderse a si misma. Mas que eso, es escasamente capaz de defenderse a si misma, ya sea arrojando energía, o empujando ampliamente a su enemigo. \n" +
                " Cuando el jugador encuentra a Rom, es el momento definitorio en el que la historia de Bloodborne va de una narrativa sobre caza de bestias a un repentino entendimiento que nosotros, los jugadores, apenas hemos arañado la superficie de una verdad mucho mas oscura. Pero Rom no es un Grande totalmente desarrollado. Micolash en su discurso al Cosmos, menciona que le otorguen ojos como a Rom.  \"Plántanos ojos en nuestros cerebros para limpiar nuestra bestial idiotez\".  Con ojos plantados en su cerebro para limpiar su idiotez, Rom ascendió para convertirse en uno. \n" +
                "“Vacuo” es definido en el Diccionario de Oxford como “Tener o mostrar falta de pensamiento o inteligencia, sin mente”. La palabra viene del Latin “vacuus” que sifnifica, vacio. Junto con el sufijo “ous” (Vacuous en ingles) que significa “por la naturaleza de”\n" +
                "\n" +
                "De donde viene Rom? Quien es ella? Cual es su relación con el grande Kos?....";

        lore_2 = "“Si es sangre lo que te interesa, deberías probar la Iglesia de la Sanación. La iglesia controla todo el conocimiento del suministro de sangre y todas las variedades de sangre.  A través del valle de Yharnam del Este, yace la ciudad de la Iglesia de la Sanación conocida como Cathedral Ward. Y en sus profundidades esta la vieja Gran Catedral, el lugar de nacimiento de la sangre especial de la Iglesia de la Sanación, o al menos, eso dicen. Los yharnamitas no comparten mucho con forasteros.  Normalmente no te dejarian acercarte a este lugar, pero… Hoy es noche de Caceria. Esta podria ser tu chance…”\n" +
                "                                                                                                                                                                     -Gilbert.\n" +
                "\n" +
                "Esto es el primer objetivo concreto del Cazador que manejamos. Llegar a la Iglesia de la Sanacion y buscar respuestas. Esta es una institución que, técnicamente no rige sobre Yharnam, actúa como ancla y estructura central de la ciudad. Es desde allí, que el arte del suministro de sangre, el arte por el cual Yharnam seria famoso, apareció por primera vez. Con el uso de la sangre especial de la Iglesia de la Sanación, fueron capaces de curar cualquier enfermedad, formando una religión devota a la adoración de Dioses y a la Sangre. Cuando los cuentos de las propiedades curativas de la sangre de Yharnam se difundieron, aquellos que sufrian enfermedades incurables, a menudo viajaban para buscar su ultima chance de salvación. Justamente nuestro personaje al principio del juego, llega a Yharnam buscando esto mismo. \n" +
                "Pero que es la iglesia de la Sanacion? De donde viene? Y mas importante aun, cual es el secreto detras de su sangre especial? \n" +
                "El primer miembro de la Iglesia que encontramos y que esta “cuerdo”  es Alfred el Ejecutor, de el aprendemos mas sobre las raíces de la Iglesia de la Sanación. \n" +
                "“La Iglesia es la base de la sanación por sangre. Bueno, yo soy un simple cazador, poco conocedor de las idas y venidas de la Institución. Pero he oído que el medio sagrado de la sanación por sangre es venerado en la catedral principal. Y que los consejeros de la vieja Iglesia, residen en el alto estrato de Cathedral Ward. La tumba de los dioses, tallada bajo Yharnam, debería ser familiar para todo cazador. Bien, una vez, un grupo de jóvenes escolares de Byrgenwerth descubrieron un medio sagrado en las profundidades de la tumba. Esto resulto en la fundación de la Iglesia y al establecimiento de la Sanacion por Sangre”.\n" +
                "\n" +
                "La corta historia es que un grupo  de escolares descubrieron sangre de increible poder en las tumbas subterraneas, especificamente, descubrieron la Sangre Antigua. Esta, y el conocimiento de los Grandes que existieron, llevaron a una revolucion en las teorias de la Universidad y sus experimentos. Pero el Maestro WIllem, estaba en desacuerdo con la idea de usar la Sangre Antigua de los Grandes para hacer avanzar a la humanidad.\n" +
                "\n" +
                "“Teme a la Sangre Antigua”- Maestro Willem a Laurence \n" +
                "\n" +
                "Esto trajo al cisma de Byrgenwerth, la ruptura de la institucion y a la fundacion de la Iglesia de la Sanacion. Laurence se convirtio en el Primer Vicario, fundando una nueva religion y prometiendo una cura a cualquier enfermedad a traves de su milagrosa administracion de Sangre. \n" +
                "Una nota afuera de la Gran Catedral reza: “Heredero al ritual de la sangre, encargado de la ministracion. Pon tu mano en la sagrada cobertura del altar e inscribe el adagio del Maestro Laurence en tu carne”\n" +
                "Laurence y su ministracion de Sangre, trajeron una nueva era a la cultura de Yharnam, una cultura de adoracion a la Sangre, propagada a toda la poblacion. \n" +
                "\n" +
                "Pero con la sangre manchada de los Grandes fluyendo en venas humanas, el Flagelo de la Bestia vino a Yharnam. Aquellos que fueron ministrados por la Sangre Antigua fueron permeables a ceder a los efectos del Flagelo. En respuesta a esto, Gehrman, uno de los hombres que se habia ladeado con Laurence en el Scisma, fundo el Taller. Ubicado en una area oculta de la parte superior de Cathedral Ward, el taller era un lugar de entrenamiento para los guerreros de elite, despachados por la Iglesia para cazar las bestias y prevenir que el panico se desparrame por la poblacion. \n" +
                "\n" +
                "El atuendo de Cazador lee: “Uno de los articulos estandar del atuendo del cazador confeccionado en el Taller. Una buena pieza que provee defensa estable a cualquiera que se enfrente a la bestial amenaza de Yharnam. Permitiendo asechar a las bestias sin ser visto, cubriendose en la noche”\n" +
                "\n" +
                "La ultima oracion es la mas importante. Originalmente, el taller era probablemente una institucion secreta. Los cazadores no usaban simbolos y no tenian uniforme, solo la “Saw Hunter Badge” (Que encontramos al principio en un cadaver detras del chancho en las alcantarillas de Yharnam) esta misma era para identificarse entre ellos, los cazadores. Que lee entre otras cosas “[...] El taller ya no existe, y ningun grupo reconoce esta insignificante insignia”.  Operaban bajo la oscuridad, eliminando a los Yharnamitas que habian sucumbido al Flagelo de la Bestia, probablemente mas como una fachada que otra cosa; lo que sea para prevenir que el publico en general sea consciente que la sangre que estaban administrando los transformaba en monstruos.\n" +
                "\n" +
                "Pero que hay de Maria? Segun el traje de Maria: “Entre los primeros cazadores, todos los estudiantes de Gehrman, estaba la cazadora Maria. Maria esta distantemente relacionada con la reina no-muerta, pero tenia una gran admiracion por Gehrman, inconsciente de su curiosa mania”\n" +
                "\n" +
                "Nacida en Cainhurst, Maria era una hermosa mujer, no quedaban dudas aun asi, bajo los estandares de Cainhursst. Si bien era familiar de la Reina, para los Nobles aristocratas de Cainhurst, esto significaba muy poco.\n" +
                "A diferencia del resto de la gente, sin embargo, Maria odiaba el uso del armamento de sangre, como dice en la Rakuyo: “Esta espada se alimenta no de sangre, pero en cambio, demanda gran destreza.[...]”\n" +
                "Asi y todo, luego de los eventos de la Aldea Pesquera, Lady Maria no podia soportar blandir un arma. Cuando ella y Gehrman obtuvieron al Huerfano para Byrgenwerth, Maria tiro la Rakuyo al pozo de la Aldea. “Un dia, abandono su amada Rakuyo, tirandola en un oscuro pozo, cuando no podia soportarlo mas”\n" +
                "\n" +
                "Nosotros como jugadores, oimos por primera vez de Lady Maria de los pacientes del Edifiio lectivo de la Pesadilla. Ellos la llaman y hablan de ella con una genuina admiracion e incluso amor. Le piden que sostenga su mano o los ayude, que cuide de ellos.\n" +
                "\n" +
                "“Llave al balcon del primer piso del edificio lectivo. Lady Maria de la Torre Astral le dio esto a su paciente, Adeline. Maria esperaba que Adeline encuentre confort en la enue brisa que transportaba el aroma de flores desde afuera, pero Adeline no podia saber de sus intenciones”- Llave del balcon.\n" +
                "\n" +
                "Parece que Maria, genuinamente se preocupaba por los pacientes de los experimentos de la Iglesia, ya que salia de sus responsabilidades para hacer que Adeline este mas comoda en su sufrimiento. SI bien los experimentos por si solos eran atroces, no habia evidencia que habia alguna intencion maliciosa contra los pacientes\n" +
                "Aunque podria ser su locura, los pacientes todos parecian estar ahi por voluntad propia, aun disculpandose por haber sido fallos en los experimentos.\n" +
                "\n" +
                "Pero eventualmente, Maria murio. Su fallecimiento marca el fin de una era, el principio de la transicion entre la vieja Iglesia y los Viejos cazadores a los nuevos… Los que nos encontramos enfrentando en el presente. Pero como murio Maria? Cuando nos la encontramos, ella esta notablemente muerta, al menos tan muerta como conscientemente podria estar. La evidencia parece apuntar a un degollamiento, ya que la sangre en su blusa parece bajar de su cuello hacia su blusa. Sumado a esto, durante su pelea, ella visiblemente se apuñala a su misma en la garganta para iniciar la segunda fase de la batalla. Esto parece apuntar a la muerte de Maria como un acto de suicidio, cortandose su propia garganta... \n" +
                "\n" +
                "Pero pausemos por un momento el relato, para hablar de otro de los que partieron con Laurence: Micolash. \n" +
                "Hay muy poca informacion sobre Micolash y la Escuela de Mensis,  que continuaria su trabajo en Byrgenwerth. Micolash fundo esta institucion en la ciudad oculta por la Iglesia, Yahar’gul. Desde aqui, Micolash estudiaria en secreto mientras supuestamente le pasaria reportes a Laurence. \n" +
                "La llave de la Superior Cathedral Ward dice: “Los estratos superiores de la Iglesia de la Sanacion estan formados por la Escuela de Mensis, ubicada en la Villa Oculta y el Coro, ocupando la parte Superior de Cathedral Ward. La Escuela de Mensis probablemente se ubico alli primero ya que su investigacion se asemeja mucho a la de Byrgenwerth y sus practicas de investigar en secreto, son similares a la estrategia de trabajo inicial de la Iglesia de la Sanacion, que en gran parte sucedia detras de escena. \n" +
                "\n" +
                "Todo cambio con el Viejo Yharnam. La sangre palida fue una horrible epidemia que se propago como incendio en tierra seca. Naturalmente, para detener la enfermedad, la Ministracion de sangre fue usada en exceso, en cada una de las victimas. Esto llevaria al Flagelo como es referenciado en la descripcion de los antidotos. “Pequeñas pildoras medicinales que contratacan el veneno. Solian tratar la sangre palida, la desconcertante enfermedad que ataco Viejo Yharnam hace mucho tiempo. Estas pildoras solo proveen alivio en el corto plazo. La enfermedad de la Sangre palida eventualmente activara la difusion del bestial flagelo”\n" +
                "Despues de Viejo Yharnam, el flagelo no pudo mantenerse en secreto. \n" +
                "El taller fue desmantelado y reemplazado por un grupo que se convertirian en los Cazadores de la Iglesia de la Sanacion, liderados por el cazador Ludwig. El taller ya no era necesario y fue sellado. Es probable que en este momento, en el que la Iglesia de la Sanacion tomo mas control sobre Yharnam, tambien comenzo a gobernar el cuerpo de la ciudad efectivamente. COn la iglesia firmemente situada en el poder como los salvadores que habian traido la Ministracion de Sangre a Yharnam, el Coro fue formado en las areas superiores de la ciudad. \n" +
                "Para este entonces la Iglesia de la Sanacion era liderada no por Laurence y Gehrman, sino por la generacion que vino despues de ellos. EL Coro reinaba sobre la Iglesia mientras que los Cazadores de Ludwig formaron las nuevas filas de la fuerza policial de la Iglesia. La Escuela de Mensis permanecio, pero probablemente alejandose mas y mas de la Iglesia con el tiempo. \n" +
                "\n" +
                "Seguramente insatisfechos de los estudios que habian realizado desde la division de la Iglesia de Byrgenwerth, el Coro comenzo a investigar la sangre de los Grandes. \n" +
                "\n" +
                "El traje del Coro detalla: “Miembros del Coro son los miembros mas altos del clero de la Iglesia de la Sanacion y escolares que continuan el trabajo que comenzo en Byrgenwerth”. No es claro exactamente cuanto de la religion de la Iglesia era simplemente usado como fachada. No es claro tampoco si el Coro realmente creia que los Grandes eran Dioses o si simplemente usaban estas cosas como una manera de legitimizar su investigacion. Ellos ciertamente reconocian que los Grandes, si no eran Dioses, ciertamente eran deidades. El nivel de detalle dado a los simbolos sagrados y los grabados en la Iglesia solo podian demostrar una veneracion hacia los Grandes como seres superiores, especificamente el Grande sin Forma, Oedon. \n" +
                "Para darle un mejor vistazo a las motivaciones del Coro y su investigacion, tomemos un momento para analizar a la Doctora Iosefka, un personaje quien el cazador protagonista conoce al comienzo de la historia.\n" +
                "\n" +
                "Bloodborne comienza con el protagonista despertando en el primer piso de la clinica de Iosefka luego de recibir su primer ministracion de sangre. Iosefka es el primer NPC que el cazador puede encontrar, luego de que el cazador muere a manos del lobo y es enviado al Sueño del Cazador, vuelve con armamento convertido en cazador. Si el jugador, vuelve por las escaleras hacia la clinica, encontraran la puerta cerrada. A traves de una hendija en la puerta vemos a una mujer vestida de blanco, con quien podemos hablar. “Estas… de cazeria? Entonces lo siento mucho, pero… No puedo abrir esta puerta. Yo soy Iosefka. Los pacientes aqui en mi clinica no deben ser expuestos a la infeccion. Se que tu puedes cazar por nosotros, por nuestra ciudad, pero lo lamento. Por favor. Esto es todo lo que puedo hacer”\n" +
                "Iosefka ayudara al cazador otorgandole con su sangre especial concentrada, capaz de curar completamente al Cazador. “Producto de un lento y cuidadoso refinamiento, esta raro frasco de sangre aparece ser un original de la clinica”. El cazador puede volver a Iosefka en cualquier momento para recolectar mas Sangre, pero solo puede acarrear un vial a la vez. Esto cambia, sin embargo, luego de la muerte del Padre Gascoigne.\n" +
                "Esta vez, cuando el cazador viene a Iosefka, no habra sangre provista. En cambio, la Doctora  nos pedira que le enviemos a todos los que no hayan sido infectados a la Clinica asi los puede tratar y curar. A partir de este punto, la Doctora hablara con un tono ligeramente mas profundo. De hecho su actriz de voz es otra persona, haciendo de esta doctora impostora (me salio un verso sin esfuerzo :P )...\n" +
                "Como dijimos, a promesa es que las personas seran tratadas como corresponde. Como recompensa para el cazador, eventualmente nos dara Elixires Azules. Descriptos como “Un liquido dudoso uilizado en extraños experimentos realizados por los altos ministradores de la Iglesia de la Sanacion”. Un item realmente tenebroso para que un comun y simple ministrador de sangre tenga en su poder. \n" +
                "Pero no es hasta que el cazador encuentra la entrada a la parte trasera de a clinica, accesible trepando en un edificio adyacente conectado con el Bosque Prohibido, que la verdad de a investigacion de Iosefka es descubierta. \n" +
                "Cualquier NPC que el cazador haya enviado en el pasado a la clinica de Iosefka, sera encontrado aqui transformado y trastornados en Celestiales, Azules Semejantes del COsmos. Si el cazador no envio a nadie a la Clinica, solo encontraran a un Celestial, localizado en el cuarto de enfermos. Tras su muerte, dropeara un frasco de la Sangre de Iosefka, posiblemente uno que estaba siendo guardado para el Cazador en uno de sus regresos. Estos son presumiblemente los restos de la verdadera Iosefka a quien el jugador conoce al prinipio del juego. Cuando subimos las escaleras hacia el piso superior de la clinica, uno de dos eventos sucedera.\n" +
                "Si el cazador sube antes  de la Luna de Sangre, la Iosefka Impostora atacara al cazador con el Baston Enroscado y una Pistola de repeticion y si su vida esta lo suficientemente baja, atacará con un Llamado del Mas Alla (Vease herramientas arcanas de Byrgenwerth) La falsa Iosefka es uno de los cuatro NPC que blandiran esta herramienta, Yurie, la miembro del Coro en Byrgenwerth, El Loco olvidado y Micolash. Podemos inferir de esta revelacion que la Falsa Iosefka es un miembro del Coro, que vino de la parte superior de Cathedral Ward para continuar con su investigacion, posiblemente debido a que por la propagacion del FLagelo de Bestias, Cathedral Ward ya no es un lugar seguro para operar. Tras matar a la Falsa Iosefka, ella dropeara una poderosa Runa Oedon. Lo que es muy interesante, es que encontraremos una version inferior de esta runa matando a Adella la Monja o, looteando de los Celestiales si la enviamos previamente a la Clinica de Iosefka. Esta coneccion solo refuerza la afiliacion de la falsa Iosefka con la Iglesia y que tenia un rango de alta importancia, claramente mayor que el de una simple monja. Pero este es solo uno de los dos posibles eventos, como ya mencionamos.\n" +
                "Si subimos despues de la Luna de Sangre, la encontraremos doblada de dolor, sobre sus codos y rodillas en una camilla: “Dios, tengo nauseas… Has sentido esto alguna vez? Esta avanzando. Puedo ver cosas… Lo sabia, soy diferente. No soy una bestia… Yo… Dios, se siente horrile, pero, comprueba que soy elegida. No lo ves? Como se retuercen dentro de mi cabeza, es, mas bien, extatico” Con suficiente tiempo para terminar su investigacion, Iosefka comenzo su ascenso. Matarla puede dropear un tercio de cordon umbilical (Posiblemente el mismo del Huerfano)\n" +
                "\n" +
                "Pero que era estos estudios? Que hacia el Coro? Como lo hacian? Esto trae al tema final de nuestro presente analisis en este capitulo: Ebrietas, hija del Cosmos. Ebrietas es encontrada en las profundidades del Orfanato, es descripta como: “La llave del Orfanato, lugar de nacimiento del Coro. El Orfanato, a las sombras de la Gran Catedral, era un lugar de estudiosos y experimentaciones, donde jovenes huerfanos se convertian en potentes pensadores ocultos para la Iglesia de la Sanacion. El Coro, que mas adelante dividirian la Iglesia de la Sanacion era una creacion para el Orfanato”.  Hemos establecido previamente que era originalmente, La Escuela de Mensis la que llevaba a cabo las investigaciones de la Iglesia en la secritud de Yahar´gul, sin embargo con el crecimiento del poder de la Iglesia luego de la limpieza del viejo Yharnam, no habia necesidad de mantener todo en secreto y un nuevo esfuerzo para esparcir la antigua sangre fue impulsado Seria el Coro quien satisfaceria esta necesidad, con el Orfanato como su laboratorio. \n" +
                "\n" +
                "Noten que el Orfanato esta localizado directamente detras de la Gran Catedral. Podemos recordar las palabras de Gilbert, mencionando que “En lo profundo de Cathedral Ward, esta la vieja Gran catedral… EL lugar de nacimiento de la sangre especial de la Iglesia de la Sanacion”. Pero la Catedral no es la fuente de la sangre. SI bien es provista al publico desde la Gran Catedral, actualmente se origina en el Orfanato. Desde Ebrietas y los Celestiales. Ebrietas, es el Grande abandonado, lo que sea que eso signifique, y estuvo en comunion y trabajo con la Iglesia en su investigacion. Encontramos multiples referencias de esto.\n" +
                "\n" +
                "“Uno de los ritos secretos del Coro. Usa fantasmas, los invertebrados conocidos como el augurio de los Grandes, para parcialmente invocar al abandonado Ebrietas. Uno de los pocos ritos que permiten a uno directamente utilizar el poder de los Grandes, y evidenciar que el Coro se habia acercado a esta antigua verdad”.\n" +
                "“Grandes calices habilitan alcances mas profundos del laberinto. El gran Caliz de Isz se convirtio en la piedra angular del Coro, la delegacion Elite de la Iglesia de la Sanacion Fue tambien el primer Gran Caliz que se llevo a la superficie desde la epoca de Byrgenwerth, y permitio al Coro, tener audiencia con Ebrietas” - Gran Caliz de Isz\n" +
                "\n" +
                "Pero quien es Ebrietas, cual es su proposito? Que investigacion permitio que la Iglesia lleve a cabo? Y que relacion tiene con los Grandes y la Sangre Antigua?\n" +
                "\n" +
                "La iglesia de la sanacion operaba en secreto en sus dias de formacion. \n" +
                "Micolash lentamente continuaba su propia investigacion de la Sangre Antigua mediante secuestros y experimentos. Laurence administraba la Sangre Antigua a los enfermos y aquellos que sucumbian al Flagelo de la besia eran eliminados bajo el manto de oscuridad por los cazadores de Gehrman. \n" +
                "Mientras esto acontecia, la Iglesia silenciosamente continuo su investigacion de los Grandes, independientes ya, de Byrgenwerth. Inicialmente el unico grande que la iglesia de la sanacion habia identigicado era Kos (o como algunos lo llaman Kosm) de las profundidades del oceano. Los exprimentos de la iglesia sobre los Grandes, por lo tanto, estaban siempre rodeados por agua, como es descripto en el Fluido Cerebral: “En los dias iniciales de la Iglesia de la Sanacion, Los Grandes estaban conectados con el oceano, asi que los pacientes cerebrales serian embebidos de agua y esperaban el aullido del mar. El fluido cerebral se mueve dentro de la cabeza, los frutos iniciales de los ojos internos”\n" +
                "\n" +
                "Era una búsqueda en vano, sin embargo, por lo que conocemos, los grandes no se originan en el mar, pero de la tierra de los Sueños y del Cosmos. Asi es como, los experimentos fueron todos fracasos. Observando los experimentos desde la torre Astral, estaba Lady Maria. \n" +
                "Luego de la masacre de la Aldea Pesquera, Maria se rehuso a cazar nuevamente. En cambio, comenzo a liderar la investigacion sobre los Grandes para la Iglesia de la Sanacion. Pero sus pensamientos nunca pudieron abandonar la naturaleza blasfema de lo que ella y Gehran habian hecho a la aldea y omo el Huerfano habia sido extirpado del utero de su madre. Ni tampoco se permitia olvidarlo.\n" +
                "\n" +
                "No toda la aldea fue destruida. Los parasitos que habia habitado su Madre Kos habian logrado infectar a los habitantes, transformandolos en “Kin” (Semejantes/Parientes/Casi Grandes) del Cosmos. Gehrman fue el primer cazador y Maria su discipula. Pueden verse en alguna forma, como los padres de todos los cazadores. Cualquiera que se llame cazador, no importa con que organizacion se asocien, es un descendiente de aquellos que mataron al Huerfano de Kos\n" +
                "“Malditas las bestias, sus hijos tambien, y sus hijos, para siempre”\n" +
                "\n" +
                "Quiza Maria era acechada por interminables pesadillas de lo que habia hecho. Quiza, en su frustracion, desesperadamente continuaba sus experimentos. Seguramente algo debia haber salido de las atrocidades que habia cometido… Pero cada uno de sus experimentos significaba otra calle sin salida. Los pacientes empezaron a notar su frustracion hacia ellos, llorando casi como disculpandose por sus fracasos, (De ellos mismos, no de Maria) suplicando por su perdon. \n" +
                "Quiza con el tiempo, ella iria perdiendo su compasion con los pacientes y se volvia mas y mas llena de culpa. Por un lado, estaba su deseo de descubrir la verdad detras de Kos y de los Grandes, que no podia detenerlo. Pero por el otro, le importaban los pacientes De la Sala de Investigaciones y no queria verlos sufrir. Ella solo veia una salida.\n" +
                "\n" +
                "“Oh, lo se muy bien. Como los secretos resuenan tan dulcemente. Solo una muerte honesta te curara ahora. Liberate de tu salvaje curiosidad” Lady Maria de la Torre Astral.-\n" +
                "\n" +
                "Y se quito su propia vida. Su muerte marco el fin de una era. Para este punto, MIcolash y la Escuela de Mensis, ya habian comenzado a alejarse mas y mas del resto de la Iglesia. Con su muerte, Gehrman descendio a un espiral de depresion y el Taller fue sellado y abandonado. La vieja y secreta Iglesia de la Sanacion habia empezado a morir, y podria haberse desmoronado completamente si no hubiese sido por los eventos de Viejo Yharnam. La iglesia siempre confio en ganar mas seguidores atraves del uso de su milagrosa sangre, y el Viejo Yharnam le dio la oportunidad perfecta para mostrar su religion a las masas. Despues de la limpieza de Viejo Yharnam, la Iglesia de la Sanacion exploto en poder y fama. No podian mas operar en secreto y necesitaban una fuente de sangre mucho mas significativa.\n" +
                "\n" +
                "“El gran Caliz de Isz se convirtio en la piedra angular del Coro, la delegacion Elite de la Iglesia de la Sanacion. Fue tambien el primer Gran Caliz traido a la superficie desde los tiempos de  Byrgenwerth y permitio al Coro tener una audiencia con Ebrietas”\n" +
                "\n" +
                "Y asi fue que el Coro nacio. Una delegacion de Elite de viejos escolares y clerigos, el coro se convertirian en los nuevos lideres defactos de la Iglesia de la Sanacion. El Coro hurgo dentro de la tumba mucho mas profundo que cualquiera desde los dias de Byrgenwerth, buscando por una mayor fuente de Sangre y una forma de llevar su investigacion al proximo nivel. Viajaron a las Ruinas de la Ciudad Ptumeriana de Isz, que no habia sido explorada desde la epoca de los escolares de Byrgenwerth. Y asi fue que se encontraron con Ebrietas, la Hija del Cosmos.\n" +
                "\n" +
                "El gran Caliz de Isz, fue reubicado en el Orfanato de la Gran Catedral y serviria como el principal laboratorio del Coro. Interesantemente vemos muchos muchos carruajes durante nuestra estadia en Yharnam. Muchos jugadores recordaran ver o dejar notas enfrente de ellos con divertidas palabras como “Infante despreciable” o cosas asi… Pero, donde estan todos los bebes? No encontramos ningun ataud en forma de niño en las calles de Yharnam, pero muchos muchos carruajes. Donde SI encontramos ataudes asi, es en la Catedral Superior. \n" +
                "\n" +
                "En el Orfanato, el Coro, en su comunion con Ebrietas, usaban su conocimiento para experimentar en los bebes que eran abandonados o enviados al Orfanato. Hasta es posible que, luego de la vasta epidemia del Flagelo, el Coro haya ido atraves del publico y juntado a todos los bebes y niños de Yharnam bajo el pretexto de protegerlos hasta que la Caza terminara. Los Yharnamitas no tendrian razon para desconfiar de la Iglesia y seguramente estaban encantados que el cuerpo gubernamental tenga semejante tacto ante la situacion.\n" +
                "\n" +
                "En los Jardines Lumen, podemos ver el resultado de sus experimentos. Observen como los Celestiales parecen crecer del suelo. Aun nel nombre Jardin parece sugerir casi una forma enfermiza en la que los Celestiales eran cosechados del suelo como plantaciones-.\n" +
                "Esta era la fuente de la sangre especial de Yharnam. Los niños que eran elevados a convertirse en Celestiales eran entonces, cosechados y usados como fuentes de sangre para la Iglesia. Una fuente renovable que permitiria que puedan proveer a toda la Ciudad con toda la Sangre que necesitase.\n" +
                "La falsa Iosefka era uno de esos investigadores, que huyo a la Clinica luego que la Catedral superior fuera perdida por el Flagelo. Lo que demuestra que era demasiado aun para que el Coro manejase, y que los investigadores probablemente hayan huido. Un investigador huyo a Byrgenwerth, el primer miembro de la Iglesia que el Cazador protagonista encuentra, Yurie, que es vista vagando el segundo piso de la mansion de Byrgenwerth. Ella inclusive utiliza una tela para cubrirse los ojos ademas de proteger su cabeza, recordandonos que: “Miembros del Coro son clerigos del mas alto rango de la Iglesia de la Sanacion y escolares que continuan el trabajo que comenzo en Byrgenwerth. La cobertura en los ojos indica su deuda a las enseñanzas del Maestro Willem, aun con sus caminos divididos.”\n" +
                "\n" +
                "El Coro tenia un enorme respeto por el Maestro Willem, aunque se hayan separado de el. Nunca hubo violencia entre las dos facciones en Byrgenwerth, solo una diferencia en filosofia que conllevo a la inevitable separacion. No es sorpresa que el Coro nunca se deshizo del Maestro Willem, realmente lo veian como una figura realmente respetada en su historia. De hecho, el Maestro habia logrado lo que el Coro desesperadamente deseaba. La ascension al nivel de los Dioses.\n" +
                "\n" +
                "Suele haber tanto enfoque en la falsa Iosefka y su Lore, que la verdadera quedo olvidada casi. La gente, fanaticos y jugadores, se sorprendieron tanto con el hecho que fue reemplazada por un impostor que se olvidaron de la original. QUien era Iosefka? COmo la impostora, ella utiliza la ropa de la Iglesia Blanca. la que nos dice: “ Estos doctores son superiores a los cazadores preventivos negros y especialistas en la ministracion de sangre y el flagelo de las bestias. Ellos creen que la medicina no es un medio de tratamiento, sino mas bien un metodo de estudio y que algunos conocimientos solo puede ser obtenido exponiendose uno mismo a la enfermedad”\n" +
                "Esto implica que Iosefka era perteneciente al Coro y una especialista en sangre experimental. Ahora pongamos el foco en la parte de atras de la clinica de Iosefka. Cuerpos han sido tirados en fosas, viales sobre viales de sangre han sido recolectados, cientos de notas han sido escritas. Tambien hay Celestiales en los bosques Prohibidos, que parecen haberse escapado de la Clinica. Como esto puede ser el trabajo de la Falsa Iosefka cuando la original no es reemplazada hasta la muerte de Gascoigne? Ademas, como fue reemplazada en primer lugar? \n" +
                "No hay evidencia alguna que sea posible copiar la cara de alguien. Hay solo un tipo de mujer que tiene la misma cara que otra…. Una hermana. En la parte de atras de la Clinica, encontramos a un Celestial transformado a medias, muerto en la mesa de operaciones. Iosefka no es una inocente doctora, ella es quien invento el proceso. Esto explica porque uno de los Viales de Iosefka puede ser encontrado en la Pesadilla de Mensis, ya que estos compartian sus investigaciones con el Coro. \n" +
                "Es posible que el Frasco de sangre de Iosefka sea, por si mismo, la llave a la transformacion en Celestial, el original de la Clinica. Quien sabe lo que podria haber pasado si consumiamos mas cantidad de este si continuaba entregandonoslo.\n" +
                "\n" +
                "Cuando la falsa Iosefka huyo a la Clinica, trajo con ella un artefacto que el Coro habia recuperado de Byrgenwerth, el Cordon del Huerfano. La falsa Iosefka buscaba ascender tal como el Maestro Willem lo habia hecho, alineando su cerebro con ojos en la forma que el habia hecho hace tantos años. \n" +
                "“Oh, como se retuercen dentro de mi cabeza, es, mas bien, extatico” De hecho no esta para nada embarazada, pero en cambio, se le ha acabado el tiempo para continuar sus experimentos. En un ultimo esfuerzo, ella se come el Cordon. Pero no funciona, ya que cuando la matamos, vemos que sangra rojo (no blanco como haria un Grande o Semejante “Kin”)\n" +
                "\n" +
                "“Busca la sangre palida para trascender la caceria”  es la primera nota que encontramos. Muchos jugadores han notado que hay ciertos enemigos que no sangran rojo, pero un claro y casi palido liquido. Sin embargo, esto no es especificamente, Sangre Palida. Si esto fuera realmente sangre de los Grandes, habria unas cuantas que deberian sangrar palido, pero de hecho lo hacen en rojo: Amygdala, el Huerfano, La nodriza y la Presencia Lunar. \n" +
                "Hay, sin embargo, algunos que si sangran lo que el autor llama “Suero”: Celestiales, chupadores de cerebros, el Maestro Willem, Rom y Ebrietas. Rom, un mortal ascendido, sangra rojo si el cazador ataca su estomago, tambien sus esbirros. Pero si el cazador ataca los ojos y cabeza de Rom o sus progenitores, ellos sangran el Suero de los Semejantes. Esto no es sangre de los Grandes, sino mas bien de los semejantes del Cosmos, aquellos que una vez fueron mortales, pero ascendieron a convertirse semejantes de los Grandes. \n" +
                "Notemos como Ebrietas es mencionada como la HIJA del Cosmos. Pero esto no tiene sentido, ya que cada Grande pierde su hijo. En cambio, los Grandes anhelan sustitutos.\n" +
                "\n" +
                "Ebrietas fue posiblemente Ptumeriana, como es encontrada por los escolares en la ciudad Ptumeriana. Es muy bien documentado que los Pyumerianos investigaron y experimentaron con la Sangre Antigua lo que los llevo a la ascension mientras se acercaban a la misteriosa Verdad, sin embargo, fueron derribados antes que realmente pudieran ascender a ser Grandes.\n" +
                "El flagelose desparramo entre la gente, la Luna Sangrienta se elevó. Los Grandes descendieron y un utero fue dejado fecundado. EL embarazo de Yharnam con Mergo fue un fracaso, asi que, en busca de un sustituto, Ebrietas, posiblemente una Investigadora Ptumeriana, ascendio al nivel de los Grandes. \n" +
                "Es muy interesante como Ebrietas es repetidamente referida como la que fue dejada atras. Ebrietas no es una verdadera Grande. En cambio fue ascendida a “Kin”, a Semejante, tal como lo hizo Willem. \n" +
                "Los Ptumerianos eran antiguos, quien sabe cuanto tiempo le llevo el desarrollar su forma actual en la que la encontramos… Quiza en miles de años, el Maestro Willem se hubiese visto muy similar a ella… \n" +
                "\n" +
                "Ebrietas fue abandonada… como los Grandes luego de la devastacion de Pthumeru. Asi que espero en el laberinto, preocupandose por los Fantasmas, pequeñas criaturas como caracoles y babosas que eran familiares de los Grandes. Y cuando los Escolares se encontraron con ella en Isz, ella finalmente tendria una conexion con el mundo exterior.\n" +
                "\n" +
                "Willem y los Escolares se reunieron con Ebrietas y comenzaron a experimentar con la Sangre Antigua, la sangre manchada de Ebrietas, sustituta hija del Cosmos. Fue a traves de Ebrietas y su sangre que lo que derribo a Pthumeru, condenaria a la ciudad de Yharnam al mismo final.\n" +
                "\n" +
                "Ebrietas obtuvo su nombre de la mariposa Ebrietas, una especie encontrada en Sudamerica, que combina la forma distorsionada de Ebrietas, siendo esta casi la de una mariposa. Cuando la encontramos, esta frente a un cadaver, el cadaver de una Araña Vacua. Recordemos que aunque algo pueda morir en el mundo de la vigilia, su subconsciente puede continuar sobreviviendo en el sueño. Ebrietas habia perdido a su hija, Rom. Es una tragedia realmente: Cada uno de los Grandes, pierde su descendencia.\n" +
                "Pero habia muchos sustitutos en los carritos de bebes de Yharnam.";


    }

    public String getLore_1() {
        return lore_1;
    }

    public void setLore_1(String lore_1) {
        this.lore_1 = lore_1;
    }

    public String getLore_2() {
        return lore_2;
    }

    public void setLore_2(String lore_2) {
        this.lore_2 = lore_2;
    }
}
